---
title: "ICPMSCode"
author: "ArielleSherbak"
date: "10/29/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE}
library(readr)
library(tidyverse)
library(janitor)
```


```{r}
icpms_data<- read.csv("Data/ICPMS_Data.csv", skip= 1, na= "N/A")

sample_key <- read.csv("Data/Sample_Key.csv", skip= 0)

RSD_data<-icpms_data %>%
  #first the rsd columns are selected and renamed with the approptiate metal isotope
  select(Cr52 = CPS.RSD,
         Cr53 = CPS.RSD.1,
         As76 = CPS.RSD.2,
         Cd111 = CPS.RSD.3,
         Cd114 = CPS.RSD.4,
         Pb208 = CPS.RSD.5,
         Ge_RSD = CPS.RSD.7,
         Sample.Key)%>%
  
  pivot_longer(1:6, 
               names_to="metal", 
               values_to = "RSD")


ICPMS_tidy <- icpms_data %>%
  select(Cr52 = CPS,
         Cr53 = CPS.1,
         As76 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge72 = CPS.7,
         Sample.Key)%>%
  
  pivot_longer(1:6, 
               names_to="metal", 
               values_to = "CPS")%>%

mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
       CPS=CPS/Ge72)%>%
  select(-Ge72)


all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$metal==ICPMS_tidy$metal)


ICPMS_merged <- merge(ICPMS_tidy, sample_key) %>%
  clean_names()
```

```{r}
### rm(list=setdiff(ls(), "ICPMS_merged"))
write.csv(ICPMS_merged, file = "data/ICPMS_merged")

```


```{r}
AA_Data <- read_csv("Data/AA_Data.csv", skip = 4)

AA_tidy<-AA_Data%>%
  rename(Sample.Key ="Sample Key")%>%
  rename(percentRSD = "%RSD")


AA_tidy$percentRSD[AA_tidy$percentRSD == "HIGH"] <- 999.99

AA_tidy$Sample.Key[AA_tidy$Sample.Key == "check10"] <- 80
AA_tidy$Sample.Key[AA_tidy$Sample.Key == "Sample Blank"] <- 90

AA_tidy$Sample.Key <- as.numeric(AA_tidy$Sample.Key)
AA_tidy$percentRSD <- as.numeric(AA_tidy$percentRSD)


AA_merge<-merge(sample_key, AA_tidy)


##clean_names(AA_tidy, case="snake")
 

write.csv(AA_merge, file = "data/tidy_AA.rds")
















```
