---
title: "Week2AA"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
```

```{r, warning=FALSE}

AA<-read_csv("~/ICPMSArielle/Data/AA_DATA.csv") %>%
  mutate(percent_rsd = as.numeric(percent_rsd)*100)

```

```{r}
sample_sites <- unique(filter(AA, site != "MB", site != "")$site)
```

```{r Calibration}

  #filtering for a single metal then selecting variables of interest
cal <- AA %>%
  filter(type != "Sample", percent_rsd != "HIGH") %>%
  select(mean_abs, percent_rsd, concentration)
#weighted linear regression
w <- 1/(cal$mean_abs*cal$percent_rsd)^2
model <- lm(cal$mean_abs ~ cal$concentration, weights = w)
slope <- model$coefficients[2]
intercept <- model$coefficients[1]
slope_std <- summary(model)$coefficients[2,2]
intercept_std <- summary(model)$coefficients[1,2]
plot(cal$mean_abs ~ cal$concentration,
       xlab = paste("[ ] of Chromium (ppm)"),
       ylab = "Mean Abs") +
    abline(model, col = "green") +
    title(paste("Calibration for Chromium"))
equation <- tibble(metal = "Chromium", slope, slope_std, intercept, intercept_std)
cal <- rbind(equation)
cal

```

```{r}

##Same as ICPMS from James code, adjusted for AA dataset
sample_analysis <- function(unique_site){ 
#initiated "for loops" to select a specific sample and a specific metal
  concentration_data <- NULL
  sample <- filter(AA, site == unique_site)
  data <- NULL
  for (ID in sample$sample_key){
    sample_dataAA <- filter(sample, sample_key == ID)
    #convert the cps readings into concentrations
      #sample analysis
    m <- cal$slope
    b <- cal$intercept
    y <- sample_dataAA$mean_abs
    b_e <- cal$intercept_std
    m_e <- cal$slope_std
    x <- (y-b)/m #The units are dependent on the calibration standards (Kg/mL)
    
    RSD <- ((sample_dataAA$percent_rsd/100)*sample_dataAA$mean_abs)
    absorption <- sample_dataAA$mean_abs
 #propagate the error in the concetration
      #error propagation
    e_yb <- sqrt((RSD)^2 + (b_e)^2) #error in y-b from calibration
    yb <- absorption - b
    e_x <- x*sqrt((e_yb/yb)^2 +(m_e/m)^2) 
    #error in x from calibration
      #if the "site is not eh method blank, store the concentration data
    data <- rbind(data, data_frame(sample_key = ID, x, e_x))
    if(unique_site != "MB"){
      concentration_data <- data_frame(sample_key = sample_dataAA$sample_key,
                                         analyst = sample_dataAA$analyst,
                                         metal = "Chromium",
                                         site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
        rbind(concentration_data)
    }
     #if the site is the method blank, average the concentrations and then store the data
    if (unique_site == "MB"){
      x <- mean(data$x)
      e_x <- sd(data$x)
      concentration_data <- data_frame(metal = "Chromium",
                                       site = unique_site,
                                       conc_dil = x,
                                       conc_dil_error = e_x) %>%
        rbind(concentration_data)
  }
  }
  
  
  return(concentration_data)
}

```


```{r}
#create a function that runs a different function on each of the soil sample sites

#inputs: a function
#outputs: a data frame with the function outputs from each site

run_sites <- function(Function){
  value <- NULL
  for (site in sample_sites){
    site_value <- Function(site)
    value <- rbind(site_value, value)
  }
  return(value)
}



```

```{r}
#analyze the method blank and all the samples
MB<- sample_analysis("MB") #ug/kg
uncor_sample<- run_sites(sample_analysis)
#values do not account for dilutns
MB
uncor_sample


```


```{r}
sample_data_mb <- NULL

  conc_dil_blanked<- uncor_sample$conc_dil-MB$conc_dil
  
  #error propogation: subtraticoon of MB
  conc_dil_blanked_error <- sqrt((uncor_sample$conc_dil_error)^2 +(MB$conc_dil_error)^2)
  
  sample_data_mb<-uncor_sample%>%
    mutate(conc_dil_blanked, conc_dil_blanked_error)%>%
    rbind(sample_data_mb)


sample_data_mb

```


```{r}
#define the dilution factors and measuremnt errors
#error propagation
vol_e <- 1
mass_e <- 0.001
dil_1010_e <- sqrt(1^2 + 10^2)
dil_e <- sqrt((dil_1010_e/1010)^2 + (1/10)^2) #error in 101 dilution factor

#correct for dilutions and propagate error
sample_data <- merge(AA, sample_data_mb) %>%
  unique() %>%
  mutate(conc_blanked = conc_dil_blanked*(total_volume/1000)/(mass_of_soil/1000),
         #101 is the factor diluted by at OHSU to make the solutions dilute enought to run the ICPMS on
         conc_blanked_error = conc_blanked *   
           sqrt((conc_dil_blanked_error/conc_dil_blanked)^2 + 
           (dil_e/101)^2 +
           (mass_e/mass_of_soil)^2 +
           (vol_e/total_volume)^2),
         conc_unblanked = conc_dil*(total_volume/1000)/(mass_of_soil/1000)*101,
         conc_unblanked_error = conc_unblanked*
           sqrt((conc_dil_error/conc_dil)^2 +
                  (dil_e/101)^2 +
                  (mass_e/mass_of_soil)^2 +
                  (vol_e/total_volume)^2)) %>%
  select(-concentration, #removing uneccesary columns
         -type,
         -mass_of_soil,
         -total_volume,
         -mean_abs,
         -percent_rsd,
         -conc_dil_blanked,
         -conc_dil_blanked_error,
         -conc_dil,
         -conc_dil_error)

```


```{r}
rm(list=ls()[!(ls()%in% c("AA", "sample_data"))])
```


```{r}
AVG_concSITE<- sample_data%>%
  filter(site!= "QC")%>%
  group_by(site)%>%
  summarise(mean_conc = mean(conc_blanked), sd_conc = sd(conc_blanked), n = n()) %>%
    mutate(CI = qnorm(0.975)*sd_conc/sqrt(n),
         lower_ci = mean_conc - CI,
         upper_ci = mean_conc + CI)
AVG_concQC<- sample_data%>%
  filter(site== "QC")%>%
  group_by(site)%>%
  summarise(mean_conc = mean(conc_blanked), sd_conc = sd(conc_blanked), n = n()) %>%
    mutate(CI = qnorm(0.975)*sd_conc/sqrt(n),
         lower_ci = mean_conc - CI,
         upper_ci = mean_conc + CI)
AVG_concALL<- sample_data%>%
  filter(site!= "QC")%>%

  summarise(mean_conc = mean(conc_blanked), sd_conc = sd(conc_blanked), n = n()) %>%
    mutate(CI = qnorm(0.975)*sd_conc/sqrt(n),
         lower_ci = mean_conc - CI,
         upper_ci = mean_conc + CI)

write.csv(sample_data, "~/ICPMSArielle/Data/AA_data2.csv")

write.csv(AVG_concSITE, "~/ICPMSArielle/Data/AAAVG_concSITE.csv")
```


```{r}
t.test2 <- function(m1,m2,s1,s2,n1,n2,m0=0,equal.variance=FALSE)
{
    if( equal.variance==FALSE ) 
    {
        se <- sqrt( (s1^2/n1) + (s2^2/n2) )
        # welch-satterthwaite df
        df <- ( (s1^2/n1 + s2^2/n2)^2 )/( (s1^2/n1)^2/(n1-1) + (s2^2/n2)^2/(n2-1) )
    } else
    {
        # pooled standard deviation, scaled by the sample sizes
        se <- sqrt( (1/n1 + 1/n2) * ((n1-1)*s1^2 + (n2-1)*s2^2)/(n1+n2-2) ) 
        df <- n1+n2-2
    }      
    t <- (m1-m2-m0)/se 
    dat <- c(m1-m2, se, t, 2*pt(-abs(t),df))    
    names(dat) <- c("Difference of means", "Std Error", "t", "p-value")
    return(dat) 
}


```


```{r}
t.test2(48.91812,23.05865445, 9.882947,7.41209171, 12, 4  )
t.test2(48.91812,16.151985, 9.882947,5.164864565, 12, 5  )
t.test2(48.91812,26.61849284, 9.882947,13.26031917, 12, 5  )
t.test2(48.91812,9.840144961, 9.882947,4.102673005, 12, 3  )
t.test2(48.91812,13.34216869, 9.882947,7.130288564, 12, 2  )
t.test2(48.91812,6.94623958, 9.882947,5.13474049, 12, 3  )

t.test2(48.91812,17.41502, 9.882947,10.24718, 12, 22  )
```

```{r}
#f-test for the icpms vs the aa
t.test2(48.91812,17.41502, 9.882947, 10.24718, 12,22 )
```
